### PR TITLE
Add support for the ADXL355 3-axis accelerometer

### PR DESCRIPTION
**Pull request by mthoren-adi**
Signed-off-by: MThoren <mark.thoren@analog.com>

# Description

Add support for the ADXL355

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

- [ ] This change requires a documentation update

# How has this been tested?

The adxl355_example.py script runs through several basic tests.

**Test Configuration**:
* Hardware: EVAL-ADXL355-PMDZ connected to Raspberry Pi Zero 2 W
* OS: ADI Kuiper Linux, updated to rpi-5.10.y kernel

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tfcollins** [comment]
Can you add a test file for the attributes and DMA data?

**Comment by mthoren-adi** [comment]
@tfcollins DMA test added, and updated dma_tests.py to specify received data as np.int64. This may have broken something else - these emulated hardware tests are failing:
FAILED test/test_adrv9002_p.py::test_adrv9002_rx_data[False-0-adi.adrv9002]
FAILED test/test_adrv9002_p.py::test_adrv9002_rx_data[False-1-adi.adrv9002]

You mentioned the channel-specific attributes might need another test fixture, I can add these when it's been created, and try it out with AD7124-8 as well. (This part does not have a test file yet, and has lots of channel-specific attributes.)

**Comment by tfcollins** [comment]
Two things:
1. Can you submit a context for emulation to [pytest-libiio](github.com/tfcollins/pytest-libiio)?
2. Can run the ADRV9002 test locally and check the returned types? You don't need hardware.

**Comment by mthoren-adi** [comment]
I may need a lesson on  pytest-libiio. But thinking about the nonzero detector, would `assert np.max(np.abs(chan)) > 0` be functionally equivalent, while preventing rollover (and not messing with types)?

test_adxl355.py with actual hardware passes, and the adrv9002 simulated hardware tests pass. Just to be sure, I was able to force the ADXL355 test to fail by hard-coding rx (in rx_tx.py) to return all zeros.

**Comment by mthoren-adi** [comment]
@tfcollins I added in the per-channel attribute tests for calibbias on each channel, the only one to which attribute_single_value applies. The others should probably use attribute_single_value_pow2 or attribute_multipe_values, and the filter_high_pass_3db_frequency attribute values are dependent on sampling frequency, so should probably use attribute_multipe_values_with_depends. (When sub_channel tests for these are added to the fixture.)
Note that I included updates from the tfcollins/channel-attr-tests, if this is messy let's discuss.

**Pull request merged**
