### PR TITLE
Jesd204 ad9371

### PR DESCRIPTION
**Pull request by Liambeguin**
# Description

It seems like on systems with dropbear as an sshserver, fs.sshfs fails to authenticate.
Using this minimal class instead lets users read files without issues.

It also allows for login with no password.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How has this been tested?

This was tested using the jesd204 status files.
```python
>>> import adi
>>> sdr = adi.ad9371(uri=hostname)
>>> print(sdr.jesd204_statuses)
{'b3000000.axi-ad9371-jesd204-tx': {'enabled': 'enabled', 'Measured Link Clock': '122.882 MHz', 'Reported Link Clock': '122.880 MHz', 'Lane rate': '4915.200 MHz', 'Lane rate / 40': '122.880 MHz', 'LMFC rate': '7.680 MHz', 'SYNC~': 'deasserted', 'Link status': 'DATA', 'SYSREF captured': 'Yes', 'SYSREF alignment error': 'No'}, 'b3020000.axi-ad9371-jesd204-rx': {'enabled': 'enabled', 'Measured Link Clock': '122.882 MHz', 'Reported Link Clock': '122.880 MHz', 'Lane rate': '4915.200 MHz', 'Lane rate / 40': '122.880 MHz', 'LMFC rate': '3.840 MHz', 'Link status': 'CGS', 'SYSREF captured': 'Yes', 'SYSREF alignment error': 'No'}, 'b6000000.axi-ad9136-jesd204-tx': {'enabled': 'enabled', 'Measured Link Clock': '184.323 MHz', 'Reported Link Clock': '184.320 MHz', 'Lane rate': '7372.800 MHz', 'Lane rate / 40': '184.320 MHz', 'LMFC rate': '23.040 MHz', 'SYNC~': 'deasserted', 'Link status': 'DATA', 'SYSREF captured': 'disabled', 'SYSREF alignment error': 'disabled'}}
```

**Test Configuration**:
* Hardware: AD9371 on a custom board
* OS: Linux 

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [X] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tfcollins** [comment]
This is a breaking change with ADI eval boards:
```
>>> sdr = adi.adrv9009(uri="ip:192.168.86.52",jesd_monitor=True)
Oops, unhandled type 3 ('unimplemented')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/pyadi-iio-jesd/adi/adrv9009.py", line 73, in __init__
    self._jesd = jesd or _import_jesd(uri) if jesd_monitor else None
  File "/tmp/pyadi-iio-jesd/adi/adrv9009.py", line 43, in _import_jesd
    return jesdadi(uri)
  File "/tmp/pyadi-iio-jesd/adi/jesd.py", line 49, in __init__
    self.fs = sshfs(address, username, password)
  File "/tmp/pyadi-iio-jesd/adi/sshfs.py", line 51, in __init__
    self.ssh.get_transport().auth_none(self.username)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 1446, in auth_none
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/auth_handler.py", line 240, in wait_for_response
    raise AuthenticationException("Authentication timeout.")
paramiko.ssh_exception.AuthenticationException: Authentication timeout.

```

**Comment by Liambeguin** [comment]
My apologies, I'll rework this and test it on a Pluto as well.

**Comment by Liambeguin** [comment]
Hi @tfcollins, 

I setup an ad9371-fmc-ebz on a zcu102 and was able to run these tests on it as well as on our custom setup. 
I'm not sure how to handle credentials properly with this, I'm not very familiar with `pytest`.
Is there a way to pass something from the `pytest` command line that would override a default value? 

Thanks,
Liam

**Comment by tfcollins** [comment]
To pass arguments you need to use the pytest_generate_tests function https://docs.pytest.org/en/stable/parametrize.html#basic-pytest-generate-tests-example

That would need to get put here: https://github.com/analogdevicesinc/pyadi-iio/blob/master/test/common.py

-Travis

**Comment by Liambeguin** [comment]
Hi @tfcollins, 

Thanks for pointing those out! I've updated the branch with your recommendation.

Liam

**Comment by Liambeguin** [comment]
Hi @tfcollins,

Did you get a chance to look at this? 
Thanks,
Liam

**Comment by tfcollins** [comment]
Sorry for the delay. One of boards broke I was testing with and was waiting for a replacement.

**Pull request merged**
