### PR TITLE
Adding Support for ADT7420-PMDZ

### PR DESCRIPTION
**Pull request by jsanbuen**
# Description

Created and tested Python Class, Example, and Test Scripts for ADT7420-PMDZ

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Hardware used is ADT7420-PMDZ connected to MAX32666FTHR, running the IIO example project for the device from no-OS repository. Codes were developed and tested using Windows OS.

**Test Configuration**:
* Hardware: ADT7420-PMDZ on MAX32666FTHR 
* OS: Windows

# Documentation

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tfcollins** [comment]
@jsanbuen thanks for the PR. Don't forget to run the linting scripts to fix formatting issues https://analogdevicesinc.github.io/pyadi-iio/dev/index.html#precommit

**Comment by jsanbuen** [comment]
Hi Travis, I have already ran the pre-commit and committed the formatting changes. It's good to go.

**Comment by tfcollins** [comment]
You need add an entry into the part index here: https://github.com/analogdevicesinc/pyadi-iio/blob/master/doc/source/devices/index.rst

**Comment by jsanbuen** [comment]
Hi Travis, I've already added it on commit d6750ca.

**Pull request merged**
