### PR TITLE
remove one underscore to match current bindings

### PR DESCRIPTION
**Pull request by jbeale1**
# Description

I found that this change allowed the code to work. The example test code ad7124_setup_example.py as described in https://wiki.analog.com/university/labs/software/precision_adc_toolbox did not work before I made this change.

Fixes # (issue)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How has this been tested?

ad7124_setup_example.py now runs correctly both locally on Raspberry Pi 3B with AD7124 on the local SPI pins, and also over the LAN from a remote host.

**Test Configuration**:
* Raspberry Pi 3B
* OS: ADI Kuiper Linux

# Documentation

No change to documentation. Now the published example works, and before it didn't.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tfcollins** [comment]
This looks fine. Just need the commit signed. See here on how to do this: https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/contributors/signing-commits.html

**Comment by jbeale1** [comment]
Hi Travis,

I wasn't able to figure out how to sign the commit I made before through the web interface. I set up my gpg key today and did two more commits which are signed; the first one un-fixing, and then again fixing the file so my fork of the repo is now correct.  Do you want me to cancel the existing pull request and make a new one, pointing to this now-signed commit?

-john

~/Documents/AD7124/pyadi-iio/adi$ git log --show-signature
commit ce4287d7337ce6de6995bd2bcf3addade9aa1460 (HEAD -> master, origin/master, origin/HEAD)
gpg: Signature made Mon 19 Sep 2022 01:13:31 PM PDT
gpg:                using RSA key FC78AFFC4301531D6DC02F95E0CD08653D6BF179
gpg: Good signature from "John Beale (github based email) ***@***.***>" [ultimate]
Author: John Beale ***@***.***>
Date:   Mon Sep 19 13:13:31 2022 -0700

    remove underscore, to match bindings

commit 0fcfe6a64b4f59f5bf04b8977315052757b80ef1
gpg: Signature made Mon 19 Sep 2022 01:09:12 PM PDT
gpg:                using RSA key FC78AFFC4301531D6DC02F95E0CD08653D6BF179
gpg: Good signature from "John Beale (github based email) ***@***.***>" [ultimate]
Author: John Beale ***@***.***>
Date:   Mon Sep 19 13:09:12 2022 -0700

    test underscore

commit d1ab181e1e1ba9411accde8983b83d0fcbc49b33
gpg: Signature made Sat 17 Sep 2022 10:34:58 AM PDT
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
Author: John Beale ***@***.***>
Date:   Sat Sep 17 10:34:58 2022 -0700

    remove one underscore to match current bindings

**Review by amiclaus — COMMENTED** [review]
Please squash all your commits into a single one.

**Comment by tfcollins** [comment]
Handled by #383

**Pull request closed without merging**
