### PR TITLE
ad4020.py: add compatibility for ad400x parts

### PR DESCRIPTION
**Pull request by threexc**
# Description

- Extend the compatible parts list to include ad4021, ad4022
- Allow passing the device name as a parameter, with ad4020 as the default
- Handle no device name or bad device name cases
- Add classes for ad4000 (supports ad4004, ad4008), ad4001 (supports ad4005), ad4002 (supports ad4006, ad4010), ad4003 (supports ad4007, ad4011)
- Import new ad400x classes in adi/__init__.py
- Add sampling_frequency setter to support variable sampling frequency
- Add test_ad4001py, test_ad4002.py, test_ad4003.py
- Add sampling_frequency tests in test_ad4020.py

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How has this been tested?

Tested against ad4020 (sanity check), ad4001, ad4002, ad4003 eval boards attached to a zedboard with kernel based on this PR: https://github.com/analogdevicesinc/linux/pull/2171

Note: This PR should not be merged until the above is merged into the ADI linux tree.

Generalized manual test flow:

1. install pyadi-iio and dependencies in venv
2. Start Python interpreter
3. `import adi`
4. Instantiate adc object, e.g. `adc = adi.ad4001(uri="ip:10.2.5.210")`
5. Check that `adc.rx()` succeeds with no warnings or errors
6. Check sampling frequency with `adc.sampling_frequency`
7. Set sampling frequency with `adc.sampling_frequency = <value>`
8. Check sampling frequency again with `adc.sampling_frequency` and confirm change successful

Automated tests for pytest-libiio added as test/test_ad4001.py and test_ad4002.py, and run from local machine using e.g.:
`pytest --hw=ad4001 -v test/test_ad4001.py --uri=ip:10.2.5.210`

**Test Configuration**:
* Hardware: Zedboard + EVAL-AD4001FMCZ/EVAL-AD4002FMCZ/EVAL-AD4003FMCZ/EVAL-AD4020FMCZ 
* OS: 

```root@zed-4:~# cat /etc/os-release 
PRETTY_NAME="Kuiper GNU/Linux 11.2 (bullseye)"
NAME="Kuiper GNU/Linux"
VERSION_ID="11.2"
VERSION="11.2 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="https://github.com/analogdevicesinc/adi-kuiper-gen"
SUPPORT_URL="https://ez.analog.com/linux-software-drivers/"

root@zed-4:~# uname -r
6.1.0-ad400x-dev-22246-g13a485c55367
```
Custom kernel based off of linux PR 2171 as mentioned above.

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [x] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by threexc** [comment]
I've looked over the doc source but it doesn't seem like there's much to update for this. Comparing against the docs for the ad936x, seems like Sphinx should just autogen the new additions.

**Comment by threexc** [comment]
@tfcollins Here's my first revision of the ad400x series support in pyadi-iio. I'm not sure what the right approach for docs is here - should I make a more generic file doc/source/devices/adi.ad40xx.rst that details how the classes each support multiple chips? It seems excessive to make a separate class for every possible chip in the set, but I could do that too.

**Comment by threexc** [comment]
Also can't assign anyone as a reviewer for some reason...

**Comment by tfcollins** [comment]
The autodoc module directive should take care of the derivative classes. Take a look at the generated doc to see if it's desirable

**Comment by threexc** [comment]
Pushed a new version with doc updates and inclusion of the parts in supported_devices.md (was failing one of the CI checks).

**Comment by threexc** [comment]
Realized that I left out emulation artifacts. Collecting them now, but it might be a bit before all of the boards have been swapped in/out and the data collected.

**Comment by threexc** [comment]
Pushed a new version that has emulation targets for each device. That should be enough to pass all of the checks, unless I'm still missing something.

**Comment by tfcollins** [comment]
Code is fine. Just fix the lint errors and we'll merge

**Comment by threexc** [comment]
Should be fixed now.

**Comment by threexc** [comment]
Missed the black formatting, but pushed another version that handles it.

**Comment by tfcollins** [comment]
Did you use precommit? Or black directly?

**Comment by threexc** [comment]
@tfcollins I used black directly to clean it up, but looks like precommit still caught stuff. The only thing that should fail now is flake8, but it's reporting that the issues are in adi/cn0532.py. I'll put in a separate PR to clear that.

**Comment by threexc** [comment]
Rebased it too. Sorry for all of the noise.

**Comment by threexc** [comment]
@tfcollins Ping. Anything you need from me now to get this merged?

**Review by mhennerich — APPROVED** [review]

**Pull request merged**
