### PR TITLE
Adding Support for AD7768-4

### PR DESCRIPTION
**Pull request by nsacut**
# Description

Created and tested Python Class, Example, and Test Scripts for AD7768-4.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Hardware used was EVAL-AD7768-4 and ZedBoard connected to laptop. Testing and development of python codes were done on a laptop running Windows 10.

**Test Configuration**:
* Hardware: EVAL-AD7768-4 and ZedBoard
* OS: Windows 10

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nsacut** [comment]
Also, tested back ad7768 (./test/test_ad7768.py) to see if changes affects it and it still passes.

**Comment by nsacut** [comment]
This pull request is also in preparation for the upcoming cn0579 support.

**Comment by tfcollins** [comment]
Code is fine. Just need to update: https://github.com/analogdevicesinc/pyadi-iio/blob/master/test/emu/hardware_map.yml to reflect new XML

**Comment by nsacut** [comment]
Update to _hardware_map.yml_ done.

**Pull request merged**
