### PR TITLE
ad4858 pyadi-iio support

### PR DESCRIPTION
**Pull request by mphalke**
Implemented ad4858 pyadi-iio device driver class and example script

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Tested with SDP-K1 board with tinyiiod Firmware

**Test Configuration**:
* Hardware: SDP-K1 (STM32 MCU)
* OS: Windows

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mphalke** [comment]
Hi All,
Any review comments?

**Comment by tfcollins** [comment]
@mphalke please make sure to add a reviewer when creating a PR. Otherwise no one is notified to review things.

**Review by tfcollins — COMMENTED** [review]
Code is fine but need the context file for new hardware.

**Comment by mphalke** [comment]
> @mphalke please make sure to add a reviewer when creating a PR. Otherwise no one is notified to review things.

Oh sure, I was not aware, so will keep in mind.

**Comment by mphalke** [comment]
> Code is fine but need the context file for new hardware.

Again same comment as I added onto ad7134 PR:
So is there a guide for creating context xml file? Is this file created automatically or manually from the IIO context information?
We don't really work on the Linux drivers much, so while supporting these drivers can we differ the iio_emu emulation context step?

**Comment by guyhoover** [comment]
Is there any syntax information on how to use the AD4858 pyadi-iio?

**Comment by tfcollins** [comment]
> Is there any syntax information on how to use the AD4858 pyadi-iio?

@guyhoover is there something outside the examples in this PR and the [general pyadi-iio](https://analogdevicesinc.github.io/pyadi-iio/) you are looking for?

**Comment by guyhoover** [comment]
Hi Travis,

I am looking for syntax to set  the sample rate and scale for the AD4858.

Guy Hoover
Staff Engineer, Product Applications
Precision Converters Group

Office   (669) 281-7522
160 Rio Robles, San Jose, CA 95134
Websites      analog.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.analog.com_&d=DwMFaQ&c=qcgNpIcxtcG4ue_U4n7GwDI5EJilZ62n5ZDvqmyyMRo&r=Vugrgdbql3Hd40gM0BtUAjsvc2Q7iU-nbmSivf55h30&m=SSam6wpY39DiCKkHH1ITEO3mczM-LhZMK3O0jjJwOz0&s=l0nAV3QH_gi7Sc5mhrc6H4K0y2K1O9eoFOmSSP_HfzY&e=>,
.

[Inline image 2]

**Comment by tfcollins** [comment]
@guyhoover the example here shows setting the sample rate https://github.com/mphalke/pyadi-iio/blob/ad4858-support/examples/ad4858_example.py setting the scale is done by just indexing into the correct channel as so:
```
dev = ad4858(uri)
dev.channel[0].scale = 1
```

**Comment by guyhoover** [comment]
Hi Travis,

What are the restrictions on setting the sample rate? Does it have to be an integer value?
For setting the scale, what scale does 1 set the ADC to? Do the numbers correspond to the AD4858 SoftSpan settings which go from 0 to 15 or do the numbers go from 1 to 16?

**Comment by tfcollins** [comment]
@mphalke can you answer @guyhoover question.

**Comment by mphalke** [comment]
> @mphalke can you answer @guyhoover question.

Hi @tfcollins I have replied to Guy Hover on email chain. Looks like Linux drivers are still under the development and once they are fully done, we would have better clarity on the IIO attributes. I can update thye pyadi-iio drivers once linux drivers are fully done.
@guyhoover Please check my email response on your queries and do let me know if you have any further queries.

**Comment by mphalke** [comment]
V1.0: Added more attributes and xml context file

1. Added additional attributes from the linux IIO drivers
2. Generated IIO xml context file for iio_emu and added in test folder

**Comment by mphalke** [comment]
@tfcollins I have added xml context file and also updated the drivers to include all linux attributes. Please review.
Looks like there is some bug in softspan attribute of linux drivers, which I will get clarified from linux developer and update pyadi-iio drivers after that.

**Comment by mphalke** [comment]
@tfcollins 
Somehow the iio-emu tests are failing for the ad4858. I double checked the test script file and also xml context and they seem to be in order. Would you be able know the reason of failure?
https://github.com/analogdevicesinc/pyadi-iio/actions/runs/5735344794/job/15542944655?pr=438#step:6:1447

**Comment by tfcollins** [comment]
> @tfcollins Somehow the iio-emu tests are failing for the ad4858. I double checked the test script file and also xml context and they seem to be in order. Would you be able know the reason of failure? https://github.com/analogdevicesinc/pyadi-iio/actions/runs/5735344794/job/15542944655?pr=438#step:6:1447

For ADC only tests you need to disable emulation for the RX specific DMA tests since it will only return zeros. Here is an example of how to disable that specific test https://github.com/analogdevicesinc/pyadi-iio/blob/master/test/test_ad9680_p.py#L7

**Comment by mphalke** [comment]
> > @tfcollins Somehow the iio-emu tests are failing for the ad4858. I double checked the test script file and also xml context and they seem to be in order. Would you be able know the reason of failure? https://github.com/analogdevicesinc/pyadi-iio/actions/runs/5735344794/job/15542944655?pr=438#step:6:1447
> 
> For ADC only tests you need to disable emulation for the RX specific DMA tests since it will only return zeros. Here is an example of how to disable that specific test https://github.com/analogdevicesinc/pyadi-iio/blob/master/test/test_ad9680_p.py#L7

Thanks Travis. I did update the test script as per above reference example and now tests seem to be passing. However, I did not understand the implication of this change. On ad7768-1 ADC test script I don't see this issue even if I don't disable emulation for Rx DMA specific tests. Could you please clarify on that? I am trying to understand how this work and in what cases this exception is needed (is it for all ADCs)?

**Comment by tfcollins** [comment]
> > > @tfcollins Somehow the iio-emu tests are failing for the ad4858. I double checked the test script file and also xml context and they seem to be in order. Would you be able know the reason of failure? https://github.com/analogdevicesinc/pyadi-iio/actions/runs/5735344794/job/15542944655?pr=438#step:6:1447
> > 
> > 
> > For ADC only tests you need to disable emulation for the RX specific DMA tests since it will only return zeros. Here is an example of how to disable that specific test https://github.com/analogdevicesinc/pyadi-iio/blob/master/test/test_ad9680_p.py#L7
> 
> Thanks Travis. I did update the test script as per above reference example and now tests seem to be passing. However, I did not understand the implication of this change. On ad7768-1 ADC test script I don't see this issue even if I don't disable emulation for Rx DMA specific tests. Could you please clarify on that? I am trying to understand how this work and in what cases this exception is needed (is it for all ADCs)?

The generic RX DMA tests perform basic analysis on the receive data. To basically sanity check the data itself. In emulation mode, if you are not using a transceiver all data will be zeros you pull back. When you have hardware this usually means something is wrong, so the test is designed to fail. The flag you added will disable the test when its run in emulation mode since it will fail by design.

**Pull request merged**
