### PR TITLE
Add support for Generic TDD Engine (TDDN)

### PR DESCRIPTION
**Pull request by podgori**
# Description

Adding support for TDDN:
- Added tddn.py in library
- Added pluto_tddn.py example script
- Updated the documentation to include the TDDN

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How has this been tested?

The example script was tested on Pluto in Phaser mode. The TDD configuration and functionality from pluto_tddn.py example was validated and tested with an oscilloscope.

# Documentation

TDDN wiki page: https://wiki.analog.com/resources/fpga/docs/axi_tdd

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by mthoren-adi — APPROVED** [review]
Approving pro-forma after discussion with Jon

**Comment by tfcollins** [comment]
@podgori how is this different than the existing TDD class?

**Comment by podgori** [comment]
This class is specific to the Generic TDD engine, the new scalable and standalone TDD IP, which aims to reduce the naming confusion around the existing TDD core built for AD9361, as well as expanding its number of output channels for systems which require more than six controlling signals (up to 32 channels). As such:
- its properties match the new TDD driver attributes
- uses a channel class with common properties per channel
- uses indexed channels

**Comment by tfcollins** [comment]
Can we replace the existing design (adi.tdd) with this one?

**Comment by podgori** [comment]
> Can we replace the existing design (adi.tdd) with this one?

As discussed, we can leave these 2 classes separate for now.

**Pull request merged**
