### PR TITLE
add support for ad7745, ad7746, ad7747

### PR DESCRIPTION
**Pull request by buha**
Signed-off-by: Darius Berghe <darius.berghe@analog.com>

# Description

add support for ad7745, ad7746, ad7747

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x]  Branch ad7746-example adds an example for this file which accesses all the attributes

**Test Configuration**:
* Hardware:
* OS: linux

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tfcollins** [comment]
This looks pretty good.

Be sure to run the pre-commit checks so the linter won't complain: https://analogdevicesinc.github.io/pyadi-iio/dev/index.html#precommit

**Comment by buha** [comment]
V2:
- ran the pre-commit hook

**Comment by buha** [comment]
V3:
- removed 2 unused imports
- moved calibscale_calibration() to _volt_channel because the voltage channel may also have the gain calibrated so the user expects their voltage channel to provide this method
- fix some Codacy warnings

**Comment by buha** [comment]
V4:
- add the missing offset capacitive channel attribute
- add a new commit with an example - capacitive length sensor demo

**Pull request merged**
