### PR TITLE
Fix/adrv9002 test

### PR DESCRIPTION
**Pull request by nunojsa**
# Description

This PR adds some fixes to the adrv9002 test suit. The profiles test were not working due to the fact that the examples profiles in
this repo were outdated with respect to the current API running on linux. Moreover, it fixes some other problems as TX/RX NCO settings that need a proper profile to be tested. Also the RX gains limits were adapted to new values used on the linux driver.

## Type of change

- [ * ] Bug fix (non-breaking change which fixes an issue)

# How has this been tested?

Ran the new tests and verified that they passed...

- [ * ] test_adrv9002_profile_write
- [ * ] test_adrv9002_nco
- [ * ] test_adrv9002_nco_write_profile

**Test Configuration**:
* Hardware: ADRV9002
* OS: Ubuntu Mate 20.04

# Checklist:

- [ * ] My code follows the style guidelines of this project
- [ * ] I have performed a self-review of my own code
- [ * ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ * ] My changes generate no new warnings

### CODE REVIEW

**Comment by tfcollins** [comment]
CI is complaining about the extra newlines in the profiles. @nunojsa do you know if removing that line breaks them or do we need to whitelist that directory from lint?

**Comment by nunojsa** [comment]
No, it should be fine to add that extra newline. The driver should ignore it anyways... I will run `pre-commit` to fix those (honestly I only run it at the last patch).

**Comment by nunojsa** [comment]
Changes in v2:
- Fix end of file in profiles

**Comment by nunojsa** [comment]
Changes in v3:
- Add missing profile file with NCO enabled...

**Pull request merged**
