### PR TITLE
Extended __repr__ of Pluto object

### PR DESCRIPTION
**Pull request by petrushy**
An improved __repr__ for the adi.Pluto() object.

Now gpg signed.

### CODE REVIEW

**Comment by tfcollins** [comment]
Can you update the commit message to include: Signed off by **
Look at the commit here as an example: https://github.com/analogdevicesinc/pyadi-iio/commit/09dd3ebb91c39e652a488b450e0202629be4727d

-Travis

**Comment by rgetz** [comment]
There is a difference between "signing" your commit with pgp/gpg ([Doc](https://help.github.com/en/github/authenticating-to-github/signing-commits)) and adding a `"Signed-off-by"` 

```
-s
--signoff
Add Signed-off-by line by the committer at the end of the commit log message.
```
which means you agree with [Developer's Certificate of Origin 1.1](https://developercertificate.org/)

It's the latter we care about.

**Comment by petrushy** [comment]
Should be properly signed now I think.

**Comment by rgetz** [comment]
It is - thanks alot.

**Pull request merged**
