### PR TITLE
rx_tx: convert format dynamically per channel basis

### PR DESCRIPTION
**Pull request by adisuciu**
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com># Description

Fixes # (issue) - 
https://ez.analog.com/sw-interface-tools/f/q-a/562754/ad7124_simple_capture-py-does-not-find-ad7124-device

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] (probably) Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How has this been tested?

- AD7124 test program - generate sine from ADALM2000 into ad7124 - test with attached test program

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tfcollins** [comment]
The following paths need to be updated
- Multi-type non_complex (ADPD188-BI uses this)
- Complex data device (PlutoSDR here)

**Comment by adisuciu** [comment]
Added another commit that uses buffer.read to get data. Then computes a dtype tuple to use with frombuffer. This prevents interleave/deinterleave mess .

Does any project really use channel interleave mode ? I would just get rid of it :sweat_smile:

**Comment by tfcollins** [comment]
@adisuciu I sent a PR to the branch. I think it simplifies the logic a bit and relies upon the built-in manipulation from channel.read in libiio itself.

**Comment by adisuciu** [comment]
I dropped the ad7124 fixes and put them in another PR
I think this is ready to be merged, unless you want to squash

**Pull request merged**
