### PR TITLE
Added colormap to waterfall

### PR DESCRIPTION
**Pull request by 777arc**

### CODE REVIEW

**Comment by tfcollins** [comment]
@777arc  just need to run the linter

**Comment by 777arc** [comment]
> @777arc just need to run the linter

All your linter says is 

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted /home/runner/work/pyadi-iio/pyadi-iio/examples/phaser/RADAR_FFT_Waterfall.py

No idea what that means

**Comment by tfcollins** [comment]
> > @777arc just need to run the linter
> 
> All your linter says is
> 
> black....................................................................Failed
> 
>     * hook id: black
> 
>     * files were modified by this hook
> 
> 
> reformatted /home/runner/work/pyadi-iio/pyadi-iio/examples/phaser/RADAR_FFT_Waterfall.py
> 
> No idea what that means

It means the code isn't formatted. Just run the litter and it will format it for you

**Comment by 777arc** [comment]
Ah didn't realize black was the name of a linter/autoformatter

**Pull request merged**
